name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test heroku-20
      run: make test-heroku-20
    - name: Test heroku-22
      run: make test-heroku-22
    - name: Test heroku-24
      run: make test-heroku-24
